name: Python application

on: [push]

jobs:

  ubuntu:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller cli.py --name "myapp" --onefile
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: myapp_ubuntu
        # Directory containing files to upload
        path: ./dist/

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller cli.py --name "myapp" --onefile
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: myapp_windows.exe
        # Directory containing files to upload
        path: .\dist\


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller cli.py --name "myapp" --onefile
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: myapp_macos.app
        # Directory containing files to upload
        path: ./dist/
