name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller cli.py --name "myapp" --onefile
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: myapp_ubuntu
        # Directory containing files to upload
        path: ./dist/
